name: Deploy or Destroy to Google Cloud

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # ✅ PROPERLY EXPORT GOOGLE_APPLICATION_CREDENTIALS
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file }}" >> $GITHUB_ENV
          echo "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=${{ steps.auth.outputs.credentials_file }}" >> $GITHUB_ENV
        shell: bash

      - name: Verify GCP Credentials File
        run: |
          echo "Using credentials file at: $GOOGLE_APPLICATION_CREDENTIALS"
          ls -la $GOOGLE_APPLICATION_CREDENTIALS
        shell: bash

      - name: Terraform Init
        run: terraform -chdir=gcloud init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION: ${{ secrets.GCP_REGION }}

      - name: Terraform Plan
        run: |
          terraform -chdir=gcloud plan \
          -var="credentials_json=${{ steps.auth.outputs.credentials_file }}" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION: ${{ secrets.GCP_REGION }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: |
          terraform -chdir=gcloud apply -auto-approve \
          -var="credentials_json=${{ steps.auth.outputs.credentials_file }}" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION: ${{ secrets.GCP_REGION }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform -chdir=gcloud destroy -auto-approve \
          -var="credentials_json=${{ steps.auth.outputs.credentials_file }}" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION: ${{ secrets.GCP_REGION }}
