name: Deploy or Destroy to Google Cloud

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          create_credentials_file: true

      - name: Terraform Init
        run: |
          cat > backend.hcl << EOL
          bucket = "tf-state-bucket-1738864366"
          prefix = "terraform/state"
          credentials = "${{ steps.auth.outputs.credentials_file }}"
          EOL
          
          terraform -chdir=gcloud init -backend-config=backend.hcl
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}

      - name: Terraform Plan
        run: |
          terraform -chdir=gcloud plan \
          -var="credentials_json=${{ steps.auth.outputs.credentials_file }}" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: |
          terraform -chdir=gcloud apply -auto-approve \
          -var="credentials_json=${{ steps.auth.outputs.credentials_file }}" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform -chdir=gcloud destroy -auto-approve \
          -var="credentials_json=${{ steps.auth.outputs.credentials_file }}" \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}